### ISSUE TITLE
Support clap 3.2

### ISSUE THREAD

**Issue by aobatact** [aobatact/clap-serde#33]

**Comment by epage** [comment]
The biggest challenge with clap 3.2 is supporting `Arg::value_parser` which takes a `ValueParser` which is effectively a `Box<TypedValueParser>`.

Options
- Only support the `TypedValueParser`s provided by clap
- Make the deserializer stateful and allow people to plug in their own factories for `TypedValueParser`

**Comment by aobatact** [comment]
I'll select the first option for now.
