### ISSUE TITLE
Provide a way to load directly into a clap app

### ISSUE THREAD

**Issue by epage** [aobatact/clap-serde#4]
Something like  `load(impl serde::Serializer) -> clap::App`

**Comment by aobatact** [comment]
Something like `load_yaml`, `load_toml` under the feature gate?

**Comment by epage** [comment]
Hmm, used to dealing with this from all of the other serde angles.  Most people are used to using the `from_str` functions provided by their serializer crate.  Some serializer crates do expose their `serde::Serializer` so you could have a `load(serializer: impl serde::Serializer)` though I would deem this a lower priority

**Comment by epage** [comment]
I've updated the issue from being about removing wrappers to about a direct load.
