### ISSUE TITLE
Only expose the Settings you have to

### ISSUE THREAD

**Issue by epage** [aobatact/clap-serde#7]
We are looking at dropping settings (see https://github.com/clap-rs/clap/issues/2717).  Limiting your support for them would ease the transition when this happens (data model transitions are a hard thing to document appropriately)

**Comment by aobatact** [comment]
Does this means to drop support of deprecated items in `ArgSettings` and `AppSettings`?
I've already remove those variant.

**Comment by epage** [comment]
I'd recommend to only expose `Arg` functions and not `ArgSettings` in preparation for us removing `ArgSettings` (ideally in clap4, maybe as late as clap5)

**Comment by aobatact** [comment]
Thank you for clarification!
I'll work it now.

**Comment by aobatact** [comment]
Is this only for `ArgSetting` or also `AppSetting`?

**Comment by epage** [comment]
`AppSettings` will also be going away but there is not an alternative API for users to call at this time.

I suggested `ArgSettings` because there is a function for every setting.
